# This configuration file defines the site's general settings, navigation bar (navbar) and footer links.
# 
# It covers 3 main sections:
# 1. General site data (e.g. title, description, keywords)
# 2. Theme (e.g. colors, fonts)
# 3. Navigation Links


#############################################################
# 1. General Site Data
#############################################################
[general]
title = "My Portfolio"
description = "Showcase of my projects."
keywords = "portfolio, projects"

footer_copyright_notice = "&copy; 2024 Your Company Name. All rights reserved."
footer_contact_info = 'Contact us: <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>'


#############################################################
# 2. Theme Options
#############################################################
# These override the default CSS styles
# Delete, comment out or set to "default" to use the default styles or to work with the styles.css file directly
# Supports hex colors, e.g. "#ff0000", color names, e.g. "red", and "default" to not override styles.css
#############################################################
[style]
accent_color = "#252a2b"                # Main color for buttons, links, and highlights
accent_hover_color = "#1d2021"          # Darker shade for hover or active states
background_color = "#d9d9d9"            # Page background, soft and neutral
background_color_card = "#ffffff"       # Card background, usually white for contrast
background_color_footer = "#f6f6f5"     # Footer background, subtly distinct
background_color_grayed_out = "#eaeaea" # Background for disabled or inactive elements
text_color = "#2b2b2b"                  # Main text color
text_color_footer = "#5c5c5c"           # Footer text, muted gray
text_color_footer_link = "#4a4a4a"      # Footer link color, matching accents
text_secondary_color = "#6d6d6d"        # Softer color for secondary text
text_light_color = "#a0a0a0"            # Light color for placeholders
text_accent_color = "#ffffff"           # Text color on accent elements, typically white
border_color = "#d9d9d9"                # Neutral color for borders and dividers

font_family = "Lato, sans-serif"         # Font for most text, modern and clean
heading_font_family = "Lato, sans-serif" # Font for headings, slightly bolder
base_font_size = "16px"                  # Default text size, readable

gallery_card_height = "250px" # Height of gallery cards
gallery_card_width = "200px"  # Width of gallery cards
gallery_grid_gap = "15px"     # Space between gallery cards


#############################################################
# 3. Navigation Links
#############################################################
# - Navbar links are specified using a [[top_link]] section for each link.
# - Footer links are specified using a [[footer_link]] section for each link.
# - Each link requires a label and target field.
# - The order in which links appear in the file determines their display order on the webpage.
#
# Supported link types:
# 1. Custom pages: Markdown files located in "custom_pages" directory to create your own pages (e.g. target = "about.md").
# 2. External links: URLs linking to outside resources (e.g., target = "https://example.com").
# 3. Special values: Built-in special pages, identified by square brackets (e.g., target = "[home]"). Available special pages: [home], [gallery].
#############################################################
[[top_link]]
label = "Home"
target = "[home]"

[[top_link]]
label = "Gallery"
target = "[gallery]"

[[top_link]]
label = "About"
target = "about.md"

[[top_link]]
label = "Contact"
target = "contact.md"

[[top_link]]
label = "Store"
target = "https://pyfolio.free.beeceptor.com/?message=This%20would%20be%20an%20external%20store%20page."

[[footer_link]]
label = "Privacy Policy"
target = "privacy.md"

[[footer_link]]
label = "Terms of Service"
target = "tos.md"

[[footer_link]]
label = "About"
target = "about.md"

[[footer_link]]
label = "Contact"
target = "contact.md"
